baseURL: "https://www.prakashbhandari.com.np"
title: Prakash's Blog ðŸ‘¨â€ðŸ’»
paginate: 10
theme: PaperMod

enableRobotsTXT: false
buildDrafts: false
buildFuture: true
buildExpired: false

googleAnalytics: G-0YH2BX9EPQ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Prakash's Blog ðŸ‘¨â€ðŸ’»
  description: "A blog about software engineering focused on web development, deployment, web programming, Docker, Microservices, Software Engineering best practices, etc"
  keywords: [Prakash's Blog, A blog about software engineering focused on web development, deployment, web programming, Docker, Microservices, Software Engineering best practices, Javascript, PHP, MySQL, microservices, docker, NodeJS, React, Angular, VueJS, laravel]
  author: Prakash Bhandari
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "/images/favicon_io/favicon.ico"
    favicon16x16: "/images/favicon_io/favicon-16x16.png"
    favicon32x32: "/images/favicon_io/favicon-32x32.png"
    apple_touch_icon: "/images/favicon_io/apple-touch-icon.png"
    #safari_pinned_tab: "images/favicon_io/favicon.ico"

  label:
    text: "Prakash's Blog"
    icon: /images/logo.png
    iconHeight: 35
  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title:   > 
      ðŸ‘‹ Iâ€™m Prakash,
    subtitle: > 
        **Software Engineer & Tech Enthusiast**
              
        ðŸ‘¨â€ðŸ’»
              
        I have 10+ years of professional experience in software engineering space. 
             
        Iâ€™m currently employed as a **Senior Software Engineer** at **[Bigtincan](https://www.bigtincan.com/company/)** 
                
        Sydney, Australia. 
              
        ðŸ˜Š

    imageUrl: "images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Prakash Bhandari
    buttons:
      - name: About
        url: /pages/about
      - name: Posts
        url: posts
      - name: Archives
        url: archives
      - name: Search
        url: search

  # home-info mode
  homeInfoParams:
    Title: " \U0001F44B  I'm Prakash, "
    Content:  >
        I am a Software Engineer with a passion for lifelong learning, problem-solving, and always improving oneself ðŸ“š
         >
        I help caring software crafters achieve technical excellence by using the best software engineering practices.
         >
        I have a solid background in using language-agnostic engineering practices such as Extreme Programming, peer programming, domain driven design and clean code. 
         >
        Over the last decade, I successfully applied these practices in many kinds of industries such as E-commerce, logistics, warehousing systems, ICT Projects, content sharing etc. ðŸ’ª
         >
        Beyond software engineering, I love reading books, and travelling. And occasionally writing the blog posts ðŸ˜Š.
  socialIcons:
    - name: github
      url: "https://github.com/dev-scripts"
    - name: linkedin
      url: "https://www.linkedin.com/in/thebhandariprakash"
    - name: twitter
      url: "https://twitter.com/TheBhandariP"
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 1
    findAllMatches: true
    keys: ["title", "permalink", "summary", "content"]
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10

    - identifier: posts
      name: Posts
      url: /posts
      weight: 20

    - identifier: search
      name: Searchs
      url: /search/
      weight: 10

    - identifier: archives
      name: Archives
      url: /archives
      weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: true
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai




